### ISSUE TITLE
关于给白技能事件的成功分支

### ISSUE THREAD

**Issue by benx1n** [UmamusumeResponseAnalyzer/UmamusumeDeserializeDB5#3]
比如CB的見解マイルール事件
选项1的成功是回复20体，弯回lv+2，失败是体力+15
目前对于技能的预处理只添加了无选项且成功失败中都有Lv这个条件，是不是可以修改为存在FailedEffect且SuccessEffect给技能Lv呢？

![image](https://user-images.githubusercontent.com/48101337/168339126-58f962be-9de1-46f7-8b94-b1ed42fa0935.png)

**Comment by benx1n** [comment]
同时也存在`金色の佳景、極まる`这样的事件
成功给技能Lv与Buff，失败只给技能Lv
这部分事件似乎是按Buff的select_index==2来判定的（有待验证）
要添加白技能的预处理话应该加在Buff后？

**Comment by EtherealAO** [comment]
> 

本来就在（也可能是新版才开始）生成的successevents.json里
```
{
    "Id": 501040801,
    "Choices": [
      [
        {
          "SelectIndex": 2,
          "Scenario": 0,
          "State": 1,
          "Effect": "スタミナ+10、パワー+10、「注目株」獲得"
        }
      ],
      [
        {
          "SelectIndex": 2,
          "Scenario": 0,
          "State": 1,
          "Effect": "「十万バリキ」のヒントLv+2、「注目株」獲得"
        }
      ],
      []
    ]
  }
```

**Comment by benx1n** [comment]
新推送的预处理代码中赛后似乎只添加了扣体，希望能将巅峰杯的道具是否刷新保留下来）

**Comment by EtherealAO** [comment]
但是那个好像不准……？

**Comment by benx1n** [comment]
测试下来基本是80-90%的概率，有些时候-10体不刷和-20体刷新倒还是需要抉择一下的
![image](https://user-images.githubusercontent.com/48101337/168411137-ae941d4d-2cb3-4491-b134-afee2ae1797c.png)
